version: '3.8'


services:

  algo_mongodb:
    container_name: '${GROUP}_mongodb'
    image: mongo:latest
    ports:
      - '${PORT_MON}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_INITDB_ROOT_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_INITDB_ROOT_PASSWORD}'
    restart: always

  algo_jupyter-notebook:
    container_name: '${GROUP}_jupyter-notebook'
    build:
      context: .
      dockerfile: Dockerfile_jupyter-notebook
    volumes:
      #- './jupyter-notebook:/home/${USER}'
      - ./jupyter-notebook:/home/algo
    ports:
      - '${PORT_JUP}:8888'
    stdin_open: true
    tty: true
