FROM ubuntu:18.04

ENV GID 1000
ENV UID 1000
ENV GROUP algo
ENV USER algo


RUN groupadd -g 1000 algo && useradd -m -u 1000 -g 1000 algo

WORKDIR /home/$USER

RUN chown -R algo:algo /home/algo
RUN apt update && \
    apt install -y python3 python3-pip
RUN pip3 install notebook

USER $USER

ENTRYPOINT jupyter notebook --ip 0.0.0.0  --port 8888 --allow-root
